# Generated by Django 4.2.4 on 2023-08-10 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_event_rename_date_joined_user_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucher",
            name="event_type",
        ),
        migrations.AddField(
            model_name="eventvoucher",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_organizer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="voucher_type",
            field=models.CharField(default="SILVER", max_length=50),
        ),
    ]
