# Generated by Django 4.1.1 on 2023-09-02 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_voucher_event_type_eventvoucher_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventvoucher",
            name="redeemed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher_redeemer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
